version: '3'
services:
  redis:
    image: 'redislabs/redisearch:latest'
    container_name: 'redis'
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - '6379:6379'
  analytics_service:
    build: 
      context: .
      dockerfile: AnalyticsService/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      redis:
        condition: service_healthy
  fibonacci_service:
    build: 
      context: .
      dockerfile: FibonacciService/Dockerfile
    ports:
      - "9090:80"
    depends_on:
      redis:
        condition: service_healthy
  leaderboard_service:
    build: 
      context: .
      dockerfile: LeaderboardService/Dockerfile
    ports:
      - "7070:80"
    depends_on:
      redis:
        condition: service_healthy